function onCreate()
  --background
  makeLuaSprite('b','bendy/postdemise',-600,-800)
  makeLuaSprite('bg','bendy/inky depths',-600,-800)
  makeLuaSprite('mid','bendy/MidGround',-600,-800)
  makeLuaSprite('fg','bendy/Foreground',-600,-400)
  makeLuaSprite('nuts','bendy/NUTS',-600,-550)
  makeLuaSprite('chains','bendy/Chains',-600,-600)
  makeAnimatedLuaSprite('sammy','bendy/SammyBg',600,50)
  addAnimationByPrefix('sammy','idle','Sam',24,true)
  objectPlayAnimation('sammy','idle',true)
  addLuaSprite('b',false)
  addLuaSprite('bg',false)
  addLuaSprite('sammy',false)
  addLuaSprite('mid',false)
  addLuaSprite('fg',true)
  addLuaSprite('chains',true)
  addLuaSprite('nuts',false)
  close(true);
  end