local allowCountdown = true
function onCreate()
  makeLuaSprite('bg','BG01',-1000,-400)
  makeLuaSprite('cutout','boi',-150,75)
  scaleObject('cutout',0.9,0.9)
  makeAnimatedLuaSprite('box','MusicBox',350,200)
  addAnimationByPrefix('box','idle','Music',24,true)
  objectPlayAnimation('box','idle',true)
  makeAnimatedLuaSprite('lights','Light(Add-Blend)',-300,-150)
  addAnimationByPrefix('lights','idle','fezt',24,true)
  objectPlayAnimation('lights','idle',true)
  makeLuaSprite('pillar','pillar',1150,-250)
  setScrollFactor('pillar',1.5,1.5)
  addLuaSprite('bg',false)
  addLuaSprite('box',false)
  addLuaSprite('cutout',false)
  addLuaSprite('lights',true)
  addLuaSprite('pillar',true)
end
function onStepHit()
  if curStep==929 then
  startVideo('bendy/1.5')
  setProperty('inCutscene',false)
  makeLuaSprite('b','bendy/postdemise',-800,-800)
  makeLuaSprite('bg','bendy/inky depths',-800,-800)
  makeLuaSprite('mid','bendy/MidGround',-800,-800)
  makeLuaSprite('fg','bendy/Foreground',-800,-400)
  makeLuaSprite('nuts','bendy/NUTS',-800,-550)
  makeLuaSprite('chains','bendy/Chains',-800,-600)
  setProperty('pillar.visible',false)
  setProperty('lights.visible',false)
  addLuaSprite('b',false)
  addLuaSprite('bg',false)
  addLuaSprite('mid',false)
  addLuaSprite('fg',true)
  addLuaSprite('chains',false)
  addLuaSprite('nuts',false)
  end
  end